version: "3"

services:
  talkspace-backend:
    image: hoanghy/talkspace-backend
    volumes:
      - mongo-data:/data/db
      - ./docker/mongo/rs-init.sh:/scripts/mongo/rs-init.sh
    ports:
      - ${PORT}:9000
    depends_on: 
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017 
    volumes:
      - mongo-data:/data/db 
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
